repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml

  - repo: local
    hooks:
      - id: lint-code
        name: Lint code with ruff
        entry: just lint
        language: system
        pass_filenames: false
        types: [python]

      - id: format-code
        name: Format code with ruff
        entry: just format
        language: system
        pass_filenames: false
        types: [python]
