language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

env:
  - DJANGO=Django==1.11
  - DJANGO=Django==2.0
  - DJANGO=Django==2.1

install:
  - pip install --use-mirrors $DJANGO
  - pip install --use-mirrors coverage coveralls

script: coverage run setup.py test

after_success: coveralls

matrix:
  exclude:
   - python: 2.7
     env: DJANGO=Django==2.0
   - python: 2.7
     env: DJANGO=Django==2.1
   - python: 3.7
     env: DJANGO=Django==1.11
