language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=Django==1.5.0

install:
  - pip install --use-mirrors $DJANGO
  - pip install --use-mirrors coverage coveralls

script: coverage run setup.py test

matrix:
  include:
   - python: 3.2
     env: DJANGO=Django==1.5.0
   - python: 3.3
     env: DJANGO=Django==1.5.0

after_success: coveralls
