# Generated by Django 3.2.7 on 2021-09-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20210927_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('prepared', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_prepared', to='tests.eater')),
                ('reviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_reviewed', to='tests.eater')),
            ],
        ),
    ]
