# Generated by Django 3.2.7 on 2023-07-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0004_eater_meal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="reviewed",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meals_reviewed",
                to="tests.eater",
            ),
        ),
    ]
